In [75]:
import numpy as np

Numpy is a python package for implementing Mathematical structures like Vectors, Matrices and n-dimensional arrays.

1. Create arrays

In [76]:
# Vectors
a = np.array([1, 2, 3])
print("Vector:")
print(a)
print("")

# Matrix
b = np.array([[1, 2], [3, 4]])
print("Matrix")
print(b)

Vector:
[1 2 3]

Matrix
[[1 2]
 [3 4]]


2. Shape and Data Types

In [77]:
print(f"Shape = {a.shape}")
print(f"Size = {a.size}")
print(f"dtype = {a.dtype}")

Shape = (3,)
Size = 3
dtype = int64


In [78]:
print(f"Shape = {b.shape}")
print(f"Size = {b.size}")
print(f"dtype = {b.dtype}")

Shape = (2, 2)
Size = 4
dtype = int64


3. Special Matrices

In [79]:
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
rand = np.random.rand(2, 2)
identity = np.eye(3)

print(zeros)
print("")

print(ones)
print("")

print(rand)
print("")

print(identity)


[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0.35297033 0.45056241]
 [0.20462517 0.56487284]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Reshaping

In [80]:
x = np.arange(9)
print(x)
print("")

x = x.reshape((3, 3))
print(x)

[0 1 2 3 4 5 6 7 8]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Arithmetic

In [81]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5 7 9]
print(a * b)   # [4 10 18]
print(a ** 2)  # [1 4 9]

[5 7 9]
[ 4 10 18]
[1 4 9]


In [82]:
# mathematical operations
x = np.random.randint(low=1, high=9, size=(4,4))
y = np.random.randint(low=1, high=9, size=(4,4))

print(np.add(x, y))
print("")

print(np.matmul(x, y))
print("")

[[ 7 16  7  9]
 [ 6 13 14  9]
 [ 6  8 15 12]
 [ 3 10  7 10]]

[[ 48 125 114  94]
 [ 53 113  94 104]
 [ 54  98 112  96]
 [ 45  94 105  80]]



6. Slicing

In [83]:
a = np.random.randint(low=0, high=100, size=(3,3))
print(a)
print("")

print(a[0, 1])   # First Row, Second Column  
print(a[:, 1])   # Second Column
print(a[2, :])   # Third Column
print(a[[0,1], :]) # First 2 rows


[[47 58 37]
 [47 46  7]
 [41 79 26]]

58
[58 46 79]
[41 79 26]
[[47 58 37]
 [47 46  7]]


In [84]:
a = np.random.randint(low=0, high=100, size=(3,3))
print(a)
print("")

print(a.sum())          
print(a.mean())         
print(a.max(axis=0))    # column-wise max
print(a.min(axis=1))    # row-wise min


[[40 33 46]
 [ 5 48 53]
 [17 36 67]]

345
38.333333333333336
[40 48 67]
[33  5 17]


7. Masking

In [85]:
a = np.random.randint(low=0, high=9, size=(4,4))
print(a)
print("")

[[6 3 8 2]
 [4 1 0 6]
 [6 8 7 5]
 [4 4 3 5]]



In [86]:
mask = a > 5  # Logical Condition or Test
print(mask)

[[ True False  True False]
 [False False False  True]
 [ True  True  True False]
 [False False False False]]


In [87]:
a[mask]  # masked elements
a[~mask] # unmasked elements

array([3, 2, 4, 1, 0, 5, 4, 4, 3, 5])

In [88]:
a[mask] = -1
print(a)

[[-1  3 -1  2]
 [ 4  1  0 -1]
 [-1 -1 -1  5]
 [ 4  4  3  5]]


8. Null & Infinity Special Values

In [97]:
a = np.random.random(size=(7,7)).astype("float16")
a[a > 0.5] = np.nan
print(a)

[[     nan      nan      nan 0.3582   0.2688   0.2708   0.1399  ]
 [0.11444  0.4846   0.1497   0.4622        nan 0.1987        nan]
 [0.1808        nan      nan      nan 0.254    0.254    0.314   ]
 [     nan 0.3015        nan      nan      nan      nan 0.1747  ]
 [     nan 0.1759   0.3594   0.2603        nan      nan      nan]
 [     nan 0.3206        nan 0.1841   0.00874       nan 0.02373 ]
 [     nan      nan      nan 0.09235  0.4888   0.001389      nan]]


In [108]:
a = np.random.random(size=(7,7)).astype("float16")
a[a > 0.5] = -1 * np.inf
print(a)

[[0.316    0.3157   0.311    0.492        -inf 0.3916       -inf]
 [0.412        -inf     -inf     -inf     -inf 0.1815       -inf]
 [    -inf     -inf 0.251        -inf     -inf     -inf     -inf]
 [    -inf 0.426        -inf     -inf 0.4072       -inf 0.155   ]
 [0.3086       -inf 0.4016       -inf 0.4844       -inf 0.05118 ]
 [0.3684       -inf     -inf 0.0998       -inf 0.3892       -inf]
 [0.4675       -inf 0.2416       -inf 0.012115 0.4375   0.2551  ]]


9. Sorting

In [ ]:
x = np.random.random(size=(10,)).astype("float16")
print(np.sort(x))

[0.1162 0.2374 0.3677 0.427  0.4468 0.5693 0.722  0.748  0.7627 0.904 ]
